=head1 NAME

tasknc - a ncurses wrapper around taskwarrior
    by mjheagle

=head1 SYNOPSIS

Usage: I<tasknc> [option] [value]

=head1 DESCRIPTION

tasknc is a simple wrapper, written in C, around the taskwarrior task manager.  

=head1 INVOCATION OPTIONS

=over 4

=item B<-h, --help>

Print the help message

=item B<-v, --version>

Print the version of tasknc

=item B<-d, --debug>

Debug mode (no ncurses gui)

=item B<-l, --loglevel> I<loglvl>

Set log level to I<loglvl>, which must be a non-negative integer.

=back

=head1 KEY BINDS

=over 4

=item B<j/k/arrowkeys>

navigation up and down

=item B<home>

go to first task

=item B<end>

go to last task

=item B<e>

edit selected task

=item B<r>

reload task list

=item B<u>

run task undo

=item B<d>

delete selected task

=item B<c>

mark selected task as complete

=item B<a>

create a new task

=item B<v/enter>

run task info on selected task

=item B<s>

resort list (prompted for sort algorithm)

=item B<y>

synchronize (run task merge and task push)

=item B<q>

exit tasknc

=item B</>

search for task

=item B<n>

go to next task result

=item B<f>

filter (prompted for filter string)

=item B<:>

open command prompt

=back

=head1 CONFIG FILE

tasknc honors a config file located at 

    $XDG_CONFIG_HOME/tasknc/config

or, if $XDG_CONFIG_HOME doesnt exist,

    $HOME/.config/tasknc/config

A documented example config can be found at /usr/share/tasknc/config.

=head1 AUTHOR

mjheagle E<lt>mjheagle8@gmail.comE<gt>
