=head1 NAME

tasknc - a ncurses wrapper around Taskwarrior
    by mjheagle

=head1 SYNOPSIS

Usage: I<tasknc> [option] [value]

=head1 DESCRIPTION

tasknc is a simple wrapper, written in C, around the Taskwarrior task manager.  

=head1 INVOCATION OPTIONS

=over 4

=item B<-h, --help>

Print the help message

=item B<-v, --version>

Print the version of tasknc

=item B<-d, --debug>

Debug mode (no ncurses gui)

=item B<-f, --filter>

Set an initial filter string

=item B<-l, --loglevel> I<loglvl>

Set log level to I<loglvl>, which must be a non-negative integer.

=back

=head1 DEFAULT KEY BINDS

=over 4

=item B<j/k/arrowkeys>

navigation up and down

=item B<home/g>

go to first task

=item B<end/G>

go to last task

=item B<e>

edit selected task

=item B<r>

reload task list

=item B<u>

run task undo

=item B<d>

delete selected task

=item B<c>

mark selected task as complete

=item B<a>

create a new task

=item B<v/enter>

run task info on selected task

=item B<s>

resort list (prompted for sort algorithm)

=item B<y>

synchronize (run task merge and task push)

=item B<q>

exit tasknc

=item B</>

search for task

=item B<n>

go to next task result

=item B<f>

filter (prompted for filter string)

=item B<:>

open command prompt

=back

=head1 CONFIGURATION

tasknc honors a config file located at 

    $XDG_CONFIG_HOME/tasknc/config

or, if $XDG_CONFIG_HOME doesnt exist,

    $HOME/.config/tasknc/config

An example config can be found at /usr/share/tasknc/config.

The configuration file contains a series of commands, which follow the format of the commands listed below.

=head1 COMMANDS

Commands are either supplied at the command prompt or listed in the configuration file.  They are used to configure tasknc to behave as you desire.

=over 4

=item B<bind> I<mode> I<key> I<function> I<args> assign I<function> to run every time a I<key> is pressed in I<mode>.  Defining I<key>s is described in the KEYS section.  I<function>s are listed below in the FUNCTIONS section.

=item

=item B<dump> will write active task info to the log file.  This is mostly for debugging.

=item

=item B<quit> will exit tasknc.

=item

=item B<reload> will force tasknc to re-import the task list.

=item

=item B<set> I<variable> I<value> will attempt to set I<variable> to a parsed I<value>.  A list of available I<variable>s are listed in the VARIABLES section.

=item

=item B<show> I<variable> will print the formatted contents of I<variable> to either stdout or the prompt area of the ncurses window.

=item

=item B<unbind> I<mode> will remove all keybindings from a specific key in I<mode>.

=item

=item B<version> will print the version info about tasknc to the prompt area of the ncurses window.

=back

=head1 VARIABLES

=over 4

=item B<follow_task> is a boolean which dictates whether the selected line will stay selected after the task is chenaged.

=item

=item B<filter_string> is the string which is currently filtering the displayed task list.

=item

=item B<log_level> is an integer variable which defines which log messages should be printed.  All messages at or below the log level are printed and written to file.

=item

Log levels:

=over 4

=item I<0> Default messages

=item I<1> Informative messages

=item I<2> Warning messages

=item I<3> Error messages

=item I<4> Debug messages

=item I<5> Verbose debug messages

=item

=back

=item B<ncurses_timeout> is an integer variable which is the number of milliseconds after which ncurses options should time out.

=item

=item B<program_name> is the string which defines the name of the program (tasknc).

=item

=item B<program_author> is the string which defines the author of tasknc.

=item

=item B<program_version> is the string which defines the version of tasknc.

=item

=item B<statusbar_timeout> is an integer variable which is the number of seconds after which the message in the statusbar times out.

=item

=item B<search_string> is the string that is currently being searched for.

=item

=item B<selected_line> is the integer number of the task which is currently selected.

=item

=item B<silent_shell> is a boolean which defines whether task command output should be printed.

=item

=item B<sort_mode> is a character which defines the sort mode.

Sort modes:

=over 4

=item I<d> due date

=item I<n> index

=item I<p> project name

=item I<r> priority

=item

=back

=item B<task_count> is the integer number of tasks which are displayed.

=item

=item B<task_format> is the string which defines the format of a displayed task.  See FORMATS for more information.

=item

=item B<task_version> is a string variable which contains the version of Taskwarrior which is being wrapped.

=item

=item B<title_format> is the string which defines the format of the title bar.  See FORMATS for more information.

=item

=item B<view_format> is the string which defines the format of the title bar of the pager when viewing a task.  See FORMATS for more information.

=item

=back

=head1 FORMATS

Formats describe how a line is printed.  Variables are denoted by a preceding $.  The variables listed in the VARIABLES section are all available.  If you would like whitespace at the beginning or end of the string, enclose it in double quotes.  Field length can be specified by a positive integer between the variable indicator ($) and the variable name.  The following additional variables are also available:

=over 4

=item B<date> displays the current date.

=item

=item B<E<gt>> marks the beginning of the right-aligned portion of the formatted section.

=back

For task formats, the following variables are available:

=over 4

=item B<description>

=item

=item B<due>

=item

=item B<project>

=item

=back

=head1 MODES

=over 4

=item B<tasklist>

=item

=item B<pager>

=item

=back

=head1 FUNCTIONS

=over 4

=item B<scroll_down> moves the cursor down

=item

=item B<scroll_end> moves the cursor to the end of the task list

=item

=item B<scroll_home> moves the cursor to the first task

=item

=item B<scroll_up> moves the cursor up

=item

=item B<complete> marks selected task as complete

=item

=item B<delete> deletes selected task

=item

=item B<edit> opens task for editing

=item

=item B<reload> reloads the task list.

=item

=item B<undo> runs 'task undo'.

=item

=item B<add> creates a new task and opens it for editing.

=item

=item B<sort> I<optarg> applies a sort defined by character I<optarg> or prompts user for sort mode wwith no arg.

=item

=item B<search> I<optarg> searches task list for string I<optarg> or prompts user for a search string with no arg.

=item

=item B<search_next> goes to the next item in the task list that matches the search string.

=item

=item B<filter> applies filter string I<optarg> or prompts user for a filter string with no arg.

=item

=item B<modify> I<optarg> runs task modify on the selected task with modifications specified in I<optarg> or gathered from a user prompt with no arg.

=item

=item B<sync> runs 'task merge && task push'.

=item

=item B<quit> exits tasknc.

=item

=item B<f_redraw> force a redraw of theh whole screen.

=item

=item B<command> I<optarg> runs the command I<optarg> or prompts the user for a command with no arg.

=back

=head1 KEYS

Keys may be specified as an integer or character.

=head1 AUTHOR

mjheagle E<lt>mjheagle8@gmail.comE<gt>

=head1 SEE ALSO

B<task(1)>
